[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ringtail"
dynamic = ["version"]
description = "Package for creating database from virtual screening files and performing filtering on results."
readme = "README.md"
license = { text = "LGPL-2.1-or-later" }
authors = [
    { name = "Forli Lab", email = "forli@scripps.edu" },
]
keywords = [
    "autodock",
    "docking",
    "drug design",
    "drug discovery",
    "molecular modeling",
    "virtual screening",
]
classifiers = [
    "Environment :: Console",
    "Environment :: Other Environment",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU Lesser General Public License v2 or later (LGPLv2+)",
    "Natural Language :: English",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.9",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Scientific/Engineering :: Chemistry",
    "Topic :: Software Development :: Libraries",
]

[project.scripts]
rt_compare = "ringtail.cli.rt_compare:main"
rt_generate_config_file = "ringtail.cli.rt_generate_config_file:main"
rt_process_vs = "ringtail.cli.rt_process_vs:main"
rt_upgrade_db = "ringtail.cli.rt_upgrade_db:main"
rt_merge = "ringtail.cli.rt_merge:main"
rt_convert_coordinates = "ringtail.cli.rt_convert_coordinates:main"

[project.urls]
Homepage = "https://github.com/forlilab/Ringtail"

[tool.setuptools.dynamic]
version = { attr = "ringtail._version.__version__" }

[tool.setuptools.packages.find]
include = ["ringtail*"]
