# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/interaction.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from list_example import list_example
from utils import get_interaction_obj_from_str, parse_list_of_items, Interaction


class InteractionWidget(QtWidgets.QWidget):
    def __init__(self, list_of_available_items, parent : QtWidgets.QWidget, active_filter=None):
        super(InteractionWidget, self).__init__(parent)
        self.interactions_type = ['R', 'H', 'vdW']
        self.items = parse_list_of_items(list_of_available_items)
        self.filtered_items = self.items
        self.filter = Interaction()
        
        if active_filter is not None:
            active_filter = get_interaction_obj_from_str(active_filter)
        
        # Active filters
        self.interaction_filter = False
        self.chain_filter = False
        self.res_name_filter = False
        self.res_id_filter = False
        self.atom_name_filter = False
        
        self.setupUi(self, active_filter=active_filter)
    
    def setupUi(self, Form, active_filter):
        Form.setObjectName("Form")
        Form.resize(542, 128)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.interactionTypeLabel = QtWidgets.QLabel(Form)
        self.interactionTypeLabel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.interactionTypeLabel.setObjectName("interactionTypeLabel")
        self.gridLayout.addWidget(self.interactionTypeLabel, 0, 0, 1, 2)
        self.interactionTypeComboBox = QtWidgets.QComboBox(Form)
        self.interactionTypeComboBox.setObjectName("interactionTypeComboBox")
        self.interactionTypeComboBox.setStyleSheet("QComboBox { combobox-popup: 0; }")
        self.interactionTypeComboBox.setMaxVisibleItems(20)
        self.gridLayout.addWidget(self.interactionTypeComboBox, 0, 2, 1, 2)
        self.wantedRadioButton = QtWidgets.QRadioButton(Form)
        self.wantedRadioButton.setObjectName("wantedRadioButton")
        self.gridLayout.addWidget(self.wantedRadioButton, 0, 4, 1, 1)
        self.unwantedRadioButton = QtWidgets.QRadioButton(Form)
        self.unwantedRadioButton.setObjectName("unwantedRadioButton")
        self.gridLayout.addWidget(self.unwantedRadioButton, 0, 5, 1, 1)
        self.interactionChainLabel = QtWidgets.QLabel(Form)
        self.interactionChainLabel.setObjectName("interactionChainLabel")
        self.gridLayout.addWidget(self.interactionChainLabel, 1, 0, 1, 1)
        self.interactionResTypeLabel = QtWidgets.QLabel(Form)
        self.interactionResTypeLabel.setObjectName("interactionResTypeLabel")
        self.gridLayout.addWidget(self.interactionResTypeLabel, 1, 1, 1, 2)
        self.interactionResNLabel = QtWidgets.QLabel(Form)
        self.interactionResNLabel.setObjectName("interactionResNLabel")
        self.gridLayout.addWidget(self.interactionResNLabel, 1, 3, 1, 1)
        self.interactionAtomNameLabel = QtWidgets.QLabel(Form)
        self.interactionAtomNameLabel.setObjectName("interactionAtomNameLabel")
        self.gridLayout.addWidget(self.interactionAtomNameLabel, 1, 4, 1, 2)
        self.interactionChainComboBox = QtWidgets.QComboBox(Form)
        self.interactionChainComboBox.setObjectName("interactionChainComboBox")
        self.interactionChainComboBox.setStyleSheet("QComboBox { combobox-popup: 0; }")
        self.interactionChainComboBox.setMaxVisibleItems(20)
        self.gridLayout.addWidget(self.interactionChainComboBox, 2, 0, 1, 1)
        self.interactionResTypeComboBox = QtWidgets.QComboBox(Form)
        self.interactionResTypeComboBox.setObjectName("interactionResTypeComboBox")
        self.interactionResTypeComboBox.setStyleSheet("QComboBox { combobox-popup: 0; }")
        self.interactionResTypeComboBox.setMaxVisibleItems(20)
        self.gridLayout.addWidget(self.interactionResTypeComboBox, 2, 1, 1, 2)
        self.interactionResNComboBox = QtWidgets.QComboBox(Form)
        self.interactionResNComboBox.setObjectName("interactionResNComboBox")
        self.interactionResNComboBox.setStyleSheet("QComboBox { combobox-popup: 0; }")
        self.interactionResNComboBox.setMaxVisibleItems(20)
        self.gridLayout.addWidget(self.interactionResNComboBox, 2, 3, 1, 1)
        self.interactionAtomNameComboBox = QtWidgets.QComboBox(Form)
        self.interactionAtomNameComboBox.setObjectName("interactionAtomNameComboBox")
        self.interactionAtomNameComboBox.setStyleSheet("QComboBox { combobox-popup: 0; }")
        self.interactionAtomNameComboBox.setMaxVisibleItems(20)
        self.gridLayout.addWidget(self.interactionAtomNameComboBox, 2, 4, 1, 2)
        # self.interactionDialogButtonBox = QtWidgets.QDialogButtonBox(Form)
        # self.interactionDialogButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        # self.interactionDialogButtonBox.setObjectName("interactionDialogButtonBox")
        # self.gridLayout.addWidget(self.interactionDialogButtonBox, 3, 4, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.populate_at_startup_comboboxes(self.items, active_filter)
        
        self.interactionTypeComboBox.currentIndexChanged.connect(self.set_interaction_type)
        self.wantedRadioButton.clicked.connect(self.set_filter_wanted)
        self.unwantedRadioButton.clicked.connect(self.set_filter_unwanted)
        
        self.interactionTypeComboBox.activated.connect(self.update_from_interaction_type)
        self.interactionChainComboBox.activated.connect(self.update_from_chain)
        self.interactionResTypeComboBox.activated.connect(self.update_from_res_type)
        self.interactionResNComboBox.activated.connect(self.update_from_res_number)
        self.interactionAtomNameComboBox.activated.connect(self.update_from_atom)
        
        # self.interactionDialogButtonBox.accepted.connect(self.get_interaction_obj)
        # self.interactionDialogButtonBox.rejected.connect(self.reject)
        # DEFAULTS
        self.wantedRadioButton.click()
        
    # CLASS METHODS
    def populate_at_startup_comboboxes(self, items, active_filter):
        if active_filter is None:
            self.interactionTypeComboBox.addItems(str(t) for t in set([x.interaction_type for x in items]))
            self.interactionTypeComboBox.insertItem(0, "Any")
            self.interactionTypeComboBox.setCurrentIndex(0)
            self.interactionChainComboBox.addItems(str(t) for t in set([x.chain for x in items]))
            self.interactionChainComboBox.insertItem(0, "Any")
            self.interactionChainComboBox.setCurrentIndex(0)
            self.interactionResTypeComboBox.addItems(str(t) for t in set([x.res_type for x in items]))
            self.interactionResTypeComboBox.insertItem(0, "Any")
            self.interactionResTypeComboBox.setCurrentIndex(0)
            self.interactionResNComboBox.addItems(str(t) for t in set([x.res_number for x in items]))
            self.interactionResNComboBox.insertItem(0, "Any")
            self.interactionResNComboBox.setCurrentIndex(0)
            self.interactionAtomNameComboBox.addItems(str(t) for t in set([x.atom_name for x in items]))
            self.interactionAtomNameComboBox.insertItem(0, "Any")
            self.interactionAtomNameComboBox.setCurrentIndex(0)
        else:
            filtered_data = self.filter_data_from_obj(active_filter)
            self.interactionTypeComboBox.addItems(str(t) for t in set([x.interaction_type for x in filtered_data]))
            self.interactionTypeComboBox.insertItem(0, "Any")
            if self.interaction_filter:
                for idx in range(0, self.interactionTypeComboBox.count()):
                    if self.interactionTypeComboBox.itemText(idx) == active_filter.interaction_type:
                        self.interactionTypeComboBox.setCurrentIndex(idx)
            else: self.interactionTypeComboBox.setCurrentIndex(0)
            self.interactionChainComboBox.addItems(str(t) for t in set([x.chain for x in filtered_data]))
            self.interactionChainComboBox.insertItem(0, "Any")
            if self.chain_filter:
                for idx in range(0, self.interactionChainComboBox.count()):
                    if self.interactionChainComboBox.itemText(idx) == active_filter.chain:
                        self.interactionChainComboBox.setCurrentIndex(idx)
            else: self.interactionChainComboBox.setCurrentIndex(0)
            self.interactionResTypeComboBox.addItems(str(t) for t in set([x.res_type for x in filtered_data]))
            self.interactionResTypeComboBox.insertItem(0, "Any")
            if self.res_name_filter:
                for idx in range(0, self.interactionResTypeComboBox.count()):
                    if self.interactionResTypeComboBox.itemText(idx) == active_filter.res_type:
                        self.interactionTypeComboBox.setCurrentIndex(idx)
            else: self.interactionResTypeComboBox.setCurrentIndex(0)
            self.interactionResNComboBox.addItems(str(t) for t in set([x.res_number for x in filtered_data]))
            self.interactionResNComboBox.insertItem(0, "Any")
            if self.res_id_filter:
                for idx in range(0, self.interactionResNComboBox.count()):
                    if self.interactionResNComboBox.itemText(idx) == active_filter.res_number:
                        self.interactionResNComboBox.setCurrentIndex(idx)
            else: self.interactionResNComboBox.setCurrentIndex(0)
            self.interactionAtomNameComboBox.addItems(str(t) for t in set([x.atom_name for x in filtered_data]))
            self.interactionAtomNameComboBox.insertItem(0, "Any")
            if self.atom_name_filter:
                for idx in range(0, self.interactionAtomNameComboBox.count()):
                    if self.interactionAtomNameComboBox.itemText(idx) == active_filter.atom_name:
                        self.interactionAtomNameComboBox.setCurrentIndex(idx)
            else: self.interactionAtomNameComboBox.setCurrentIndex(0)
            
    def update_from_interaction_type(self):        
        filtered_items = self.filter_data_from_GUI()
        if not self.chain_filter: 
            self.interactionChainComboBox.clear()
            self.interactionChainComboBox.addItems(str(t) for t in set([x.chain for x in filtered_items]))
            self.interactionChainComboBox.insertItem(0, "Any")
            self.interactionChainComboBox.setCurrentIndex(0)
        if not self.res_name_filter:
            self.interactionResTypeComboBox.clear()
            self.interactionResTypeComboBox.addItems(str(t) for t in set([x.res_type for x in filtered_items]))
            self.interactionResTypeComboBox.insertItem(0, "Any")
            self.interactionResTypeComboBox.setCurrentIndex(0)
        if not self.res_id_filter:
            self.interactionResNComboBox.clear()
            self.interactionResNComboBox.addItems(str(t) for t in set([x.res_number for x in filtered_items]))
            self.interactionResNComboBox.insertItem(0, "Any")
            self.interactionResNComboBox.setCurrentIndex(0)
        if not self.atom_name_filter:
            self.interactionAtomNameComboBox.clear()
            self.interactionAtomNameComboBox.addItems(str(t) for t in set([x.atom_name for x in filtered_items]))
            self.interactionAtomNameComboBox.insertItem(0, "Any")
            self.interactionAtomNameComboBox.setCurrentIndex(0)
        
    def update_from_chain(self):
        filtered_items = self.filter_data_from_GUI()
        if not self.interaction_filter:
            self.interactionTypeComboBox.clear()
            self.interactionTypeComboBox.addItems(str(t) for t in set([x.interaction_type for x in filtered_items]))
            self.interactionTypeComboBox.insertItem(0, "Any")
            self.interactionTypeComboBox.setCurrentIndex(0)
        if not self.res_name_filter:
            self.interactionResTypeComboBox.clear()
            self.interactionResTypeComboBox.addItems(str(t) for t in set([x.res_type for x in filtered_items]))
            self.interactionResTypeComboBox.insertItem(0, "Any")
            self.interactionResTypeComboBox.setCurrentIndex(0)
        if not self.res_id_filter:
            self.interactionResNComboBox.clear()
            self.interactionResNComboBox.addItems(str(t) for t in set([x.res_number for x in filtered_items]))
            self.interactionResNComboBox.insertItem(0, "Any")
            self.interactionResNComboBox.setCurrentIndex(0)
        if not self.atom_name_filter:
            self.interactionAtomNameComboBox.clear()
            self.interactionAtomNameComboBox.addItems(str(t) for t in set([x.atom_name for x in filtered_items]))
            self.interactionAtomNameComboBox.insertItem(0, "Any")
            self.interactionAtomNameComboBox.setCurrentIndex(0)
    
    def update_from_res_type(self):
        filtered_items = self.filter_data_from_GUI()
        if not self.interaction_filter:
            self.interactionTypeComboBox.clear()
            self.interactionTypeComboBox.addItems(str(t) for t in set([x.interaction_type for x in filtered_items]))
            self.interactionTypeComboBox.insertItem(0, "Any")
            self.interactionTypeComboBox.setCurrentIndex(0)
        if not self.chain_filter:
            self.interactionChainComboBox.clear()
            self.interactionChainComboBox.addItems(str(t) for t in set([x.chain for x in filtered_items]))
            self.interactionChainComboBox.insertItem(0, "Any")
            self.interactionChainComboBox.setCurrentIndex(0)
        if not self.res_id_filter:
            self.interactionResNComboBox.clear()
            self.interactionResNComboBox.addItems(str(t) for t in set([x.res_number for x in filtered_items]))
            self.interactionResNComboBox.insertItem(0, "Any")
            self.interactionResNComboBox.setCurrentIndex(0)
        if not self.atom_name_filter:
            self.interactionAtomNameComboBox.clear()
            self.interactionAtomNameComboBox.addItems(str(t) for t in set([x.atom_name for x in filtered_items]))
            self.interactionAtomNameComboBox.insertItem(0, "Any")
            self.interactionAtomNameComboBox.setCurrentIndex(0)
    
    def update_from_res_number(self):
        filtered_items = self.filter_data_from_GUI()
        if not self.interaction_filter:
            self.interactionTypeComboBox.clear()
            self.interactionTypeComboBox.addItems(str(t) for t in set([x.interaction_type for x in filtered_items]))
            self.interactionTypeComboBox.insertItem(0, "Any")
            self.interactionTypeComboBox.setCurrentIndex(0)
        if not self.chain_filter:
            self.interactionChainComboBox.clear()
            self.interactionChainComboBox.addItems(str(t) for t in set([x.chain for x in filtered_items]))
            self.interactionChainComboBox.insertItem(0, "Any")
            self.interactionChainComboBox.setCurrentIndex(0)
        if not self.res_name_filter:
            self.interactionResTypeComboBox.clear()
            self.interactionResTypeComboBox.addItems(str(t) for t in set([x.res_type for x in filtered_items]))
            self.interactionResTypeComboBox.insertItem(0, "Any")
            self.interactionResTypeComboBox.setCurrentIndex(0)
        if not self.atom_name_filter:
            self.interactionAtomNameComboBox.clear()
            self.interactionAtomNameComboBox.addItems(str(t) for t in set([x.atom_name for x in filtered_items]))
            self.interactionAtomNameComboBox.insertItem(0, "Any")
            self.interactionAtomNameComboBox.setCurrentIndex(0)

    def update_from_atom(self):
        filtered_items = self.filter_data_from_GUI()
        if not self.interaction_filter:
            self.interactionTypeComboBox.clear()
            self.interactionTypeComboBox.addItems(str(t) for t in set([x.interaction_type for x in filtered_items]))
            self.interactionTypeComboBox.insertItem(0, "Any")
            self.interactionTypeComboBox.setCurrentIndex(0)
        if not self.chain_filter:
            self.interactionChainComboBox.clear()
            self.interactionChainComboBox.addItems(str(t) for t in set([x.chain for x in filtered_items]))
            self.interactionChainComboBox.insertItem(0, "Any")
            self.interactionChainComboBox.setCurrentIndex(0)
        if not self.res_name_filter:
            self.interactionResTypeComboBox.clear()
            self.interactionResTypeComboBox.addItems(str(t) for t in set([x.res_type for x in filtered_items]))
            self.interactionResTypeComboBox.insertItem(0, "Any")
            self.interactionResTypeComboBox.setCurrentIndex(0)
        if not self.res_id_filter:
            self.interactionResNComboBox.clear()
            self.interactionResNComboBox.addItems(str(t) for t in set([x.res_number for x in filtered_items]))
            self.interactionResNComboBox.insertItem(0, "Any")
            self.interactionResNComboBox.setCurrentIndex(0)
    
    def filter_data_from_obj(self, active_filter):
        filtered_items = None
        if active_filter.interaction_type != None:
            self.interaction_filter = True
            filtered_items = list(filter(lambda x: x.interaction_type == active_filter.interaction_type, self.items))
        else:
            self.interaction_filter = False
        if active_filter.chain != None:
            if filtered_items is None:
                filtered_items = self.items
            self.chain_filter = True
            filtered_items = list(filter(lambda x: x.chain == active_filter.chain, filtered_items))
        else: self.chain_filter = False
        if active_filter.res_type != None:
            if filtered_items is None:
                filtered_items = self.items
            self.res_name_filter = True
            filtered_items = list(filter(lambda x: x.res_type == active_filter.res_type, filtered_items))
        else: self.res_name_filter = False
        if active_filter.res_number != None:
            if filtered_items is None:
                filtered_items = self.items
            self.res_id_filter = True
            filtered_items = list(filter(lambda x: x.res_number == active_filter.res_number, filtered_items))
        else: self.res_id_filter = False
        if active_filter.atom_name != None:
            if filtered_items is None:
                filtered_items = self.items
            self.atom_name_filter = True
            filtered_items = list(filter(lambda x: x.atom_name == active_filter.atom_name, filtered_items))
        else: self.atom_name_filter = False
        if filtered_items is None: return self.items
        return filtered_items
        
    def filter_data_from_GUI(self):
        filtered_items = None
        if self.interactionTypeComboBox.currentText() != 'Any':
            self.interaction_filter = True
            interaction_type = self.interactionTypeComboBox.currentText()
            filtered_items = list(filter(lambda x: x.interaction_type == interaction_type, self.items))
        else:
            self.interaction_filter = False
        if self.interactionChainComboBox.currentText() != 'Any':
            if filtered_items is None:
                filtered_items = self.items
            self.chain_filter = True
            chain = self.interactionChainComboBox.currentText()
            filtered_items = list(filter(lambda x: x.chain == chain, filtered_items))
        else: self.chain_filter = False
        if self.interactionResTypeComboBox.currentText() != 'Any':
            if filtered_items is None:
                filtered_items = self.items
            self.res_name_filter = True
            res_type = self.interactionResTypeComboBox.currentText()
            filtered_items = list(filter(lambda x: x.res_type == res_type, filtered_items))
        else: self.res_name_filter = False
        if self.interactionResNComboBox.currentText() != 'Any':
            if filtered_items is None:
                filtered_items = self.items
            self.res_id_filter = True
            res_n = self.interactionResNComboBox.currentText()
            filtered_items = list(filter(lambda x: x.res_number == res_n, filtered_items))
        else: self.res_id_filter = False
        if self.interactionAtomNameComboBox.currentText() != 'Any':
            if filtered_items is None:
                filtered_items = self.items
            self.atom_name_filter = True
            atom_name = self.interactionAtomNameComboBox.currentText()
            filtered_items = list(filter(lambda x: x.atom_name == atom_name, filtered_items))
        else: self.atom_name_filter = False
        if filtered_items is None: return self.items
        return filtered_items
    
    
    def set_interaction_type(self):
        self.filter.set_interaction_type(self.interactionTypeComboBox.currentText())
        
    def set_filter_wanted(self):
        if self.wantedRadioButton.isChecked():
            self.filter.set_wanted(True)
        else:
            self.filter.set_wanted(False)
    
    def set_filter_unwanted(self):
        if self.unwantedRadioButton.isChecked():
            self.filter.set_wanted(False)
        else:
            self.filter.set_wanted(True)
    
    def get_interaction_obj(self):
        self.filter.accepted = True
        self.filter.set_interaction_type(self.interactionTypeComboBox.currentText())
        self.filter.set_chain(self.interactionChainComboBox.currentText())
        self.filter.set_res_type(self.interactionResTypeComboBox.currentText())
        self.filter.set_res_number(self.interactionResNComboBox.currentText())
        self.filter.set_atom_name(self.interactionAtomNameComboBox.currentText())
        return self.filter
    
    def reject(self):
        self.filter = None
        self.filter.accepted = False

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.interactionTypeLabel.setText(_translate("Form", "Select interaction type:"))
        self.wantedRadioButton.setText(_translate("Form", "Wanted"))
        self.unwantedRadioButton.setText(_translate("Form", "Unwanted"))
        self.interactionChainLabel.setText(_translate("Form", "Chain:"))
        self.interactionResTypeLabel.setText(_translate("Form", "Res Type:"))
        self.interactionResNLabel.setText(_translate("Form", "Res #:"))
        self.interactionAtomNameLabel.setText(_translate("Form", "Atom Name:"))

    
class Interaction_Dialog(QtWidgets.QDialog):
    def __init__(self, list_of_available_items, parent : QtWidgets.QWidget, active_filter=None):
        super(Interaction_Dialog, self).__init__(parent)
        self.interactions_type = ['R', 'H', 'vdW']
        self.items = parse_list_of_items(list_of_available_items)
        self.filtered_items = self.items
        self.filter = Interaction()
        
        if active_filter is not None:
            active_filter = get_interaction_obj_from_str(active_filter)
        
        # Active filters
        self.interaction_filter = False
        self.chain_filter = False
        self.res_name_filter = False
        self.res_id_filter = False
        self.atom_name_filter = False
        
        self.setupUi(self, active_filter=active_filter)
    
    def setupUi(self, Form, active_filter):
        Form.setObjectName("Form")
        Form.resize(542, 128)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.interactionTypeLabel = QtWidgets.QLabel(Form)
        self.interactionTypeLabel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.interactionTypeLabel.setObjectName("interactionTypeLabel")
        self.gridLayout.addWidget(self.interactionTypeLabel, 0, 0, 1, 2)
        self.interactionTypeComboBox = QtWidgets.QComboBox(Form)
        self.interactionTypeComboBox.setObjectName("interactionTypeComboBox")
        self.interactionTypeComboBox.setStyleSheet("QComboBox { combobox-popup: 0; }")
        self.interactionTypeComboBox.setMaxVisibleItems(20)
        self.gridLayout.addWidget(self.interactionTypeComboBox, 0, 2, 1, 2)
        self.wantedRadioButton = QtWidgets.QRadioButton(Form)
        self.wantedRadioButton.setObjectName("wantedRadioButton")
        self.gridLayout.addWidget(self.wantedRadioButton, 0, 4, 1, 1)
        self.unwantedRadioButton = QtWidgets.QRadioButton(Form)
        self.unwantedRadioButton.setObjectName("unwantedRadioButton")
        self.gridLayout.addWidget(self.unwantedRadioButton, 0, 5, 1, 1)
        self.interactionChainLabel = QtWidgets.QLabel(Form)
        self.interactionChainLabel.setObjectName("interactionChainLabel")
        self.gridLayout.addWidget(self.interactionChainLabel, 1, 0, 1, 1)
        self.interactionResTypeLabel = QtWidgets.QLabel(Form)
        self.interactionResTypeLabel.setObjectName("interactionResTypeLabel")
        self.gridLayout.addWidget(self.interactionResTypeLabel, 1, 1, 1, 2)
        self.interactionResNLabel = QtWidgets.QLabel(Form)
        self.interactionResNLabel.setObjectName("interactionResNLabel")
        self.gridLayout.addWidget(self.interactionResNLabel, 1, 3, 1, 1)
        self.interactionAtomNameLabel = QtWidgets.QLabel(Form)
        self.interactionAtomNameLabel.setObjectName("interactionAtomNameLabel")
        self.gridLayout.addWidget(self.interactionAtomNameLabel, 1, 4, 1, 2)
        self.interactionChainComboBox = QtWidgets.QComboBox(Form)
        self.interactionChainComboBox.setObjectName("interactionChainComboBox")
        self.interactionChainComboBox.setStyleSheet("QComboBox { combobox-popup: 0; }")
        self.interactionChainComboBox.setMaxVisibleItems(20)
        self.gridLayout.addWidget(self.interactionChainComboBox, 2, 0, 1, 1)
        self.interactionResTypeComboBox = QtWidgets.QComboBox(Form)
        self.interactionResTypeComboBox.setObjectName("interactionResTypeComboBox")
        self.interactionResTypeComboBox.setStyleSheet("QComboBox { combobox-popup: 0; }")
        self.interactionResTypeComboBox.setMaxVisibleItems(20)
        self.gridLayout.addWidget(self.interactionResTypeComboBox, 2, 1, 1, 2)
        self.interactionResNComboBox = QtWidgets.QComboBox(Form)
        self.interactionResNComboBox.setObjectName("interactionResNComboBox")
        self.interactionResNComboBox.setStyleSheet("QComboBox { combobox-popup: 0; }")
        self.interactionResNComboBox.setMaxVisibleItems(20)
        self.gridLayout.addWidget(self.interactionResNComboBox, 2, 3, 1, 1)
        self.interactionAtomNameComboBox = QtWidgets.QComboBox(Form)
        self.interactionAtomNameComboBox.setObjectName("interactionAtomNameComboBox")
        self.interactionAtomNameComboBox.setStyleSheet("QComboBox { combobox-popup: 0; }")
        self.interactionAtomNameComboBox.setMaxVisibleItems(20)
        self.gridLayout.addWidget(self.interactionAtomNameComboBox, 2, 4, 1, 2)
        self.interactionDialogButtonBox = QtWidgets.QDialogButtonBox(Form)
        self.interactionDialogButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.interactionDialogButtonBox.setObjectName("interactionDialogButtonBox")
        self.gridLayout.addWidget(self.interactionDialogButtonBox, 3, 4, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.populate_at_startup_comboboxes(self.items, active_filter)
        
        self.interactionTypeComboBox.currentIndexChanged.connect(self.set_interaction_type)
        self.wantedRadioButton.clicked.connect(self.set_filter_wanted)
        self.unwantedRadioButton.clicked.connect(self.set_filter_unwanted)
        
        self.interactionTypeComboBox.activated.connect(self.update_from_interaction_type)
        self.interactionChainComboBox.activated.connect(self.update_from_chain)
        self.interactionResTypeComboBox.activated.connect(self.update_from_res_type)
        self.interactionResNComboBox.activated.connect(self.update_from_res_number)
        self.interactionAtomNameComboBox.activated.connect(self.update_from_atom)
        
        self.interactionDialogButtonBox.accepted.connect(self.get_interaction_obj)
        self.interactionDialogButtonBox.rejected.connect(self.reject)
        # DEFAULTS
        self.wantedRadioButton.click()
        
    # CLASS METHODS
    def populate_at_startup_comboboxes(self, items, active_filter):
        if active_filter is None:
            self.interactionTypeComboBox.addItems(str(t) for t in set([x.interaction_type for x in items]))
            self.interactionTypeComboBox.insertItem(0, "Any")
            self.interactionTypeComboBox.setCurrentIndex(0)
            self.interactionChainComboBox.addItems(str(t) for t in set([x.chain for x in items]))
            self.interactionChainComboBox.insertItem(0, "Any")
            self.interactionChainComboBox.setCurrentIndex(0)
            self.interactionResTypeComboBox.addItems(str(t) for t in set([x.res_type for x in items]))
            self.interactionResTypeComboBox.insertItem(0, "Any")
            self.interactionResTypeComboBox.setCurrentIndex(0)
            self.interactionResNComboBox.addItems(str(t) for t in set([x.res_number for x in items]))
            self.interactionResNComboBox.insertItem(0, "Any")
            self.interactionResNComboBox.setCurrentIndex(0)
            self.interactionAtomNameComboBox.addItems(str(t) for t in set([x.atom_name for x in items]))
            self.interactionAtomNameComboBox.insertItem(0, "Any")
            self.interactionAtomNameComboBox.setCurrentIndex(0)
        else:
            filtered_data = self.filter_data_from_obj(active_filter)
            self.interactionTypeComboBox.addItems(str(t) for t in set([x.interaction_type for x in filtered_data]))
            self.interactionTypeComboBox.insertItem(0, "Any")
            if self.interaction_filter:
                for idx in range(0, self.interactionTypeComboBox.count()):
                    if self.interactionTypeComboBox.itemText(idx) == active_filter.interaction_type:
                        self.interactionTypeComboBox.setCurrentIndex(idx)
            else: self.interactionTypeComboBox.setCurrentIndex(0)
            self.interactionChainComboBox.addItems(str(t) for t in set([x.chain for x in filtered_data]))
            self.interactionChainComboBox.insertItem(0, "Any")
            if self.chain_filter:
                for idx in range(0, self.interactionChainComboBox.count()):
                    if self.interactionChainComboBox.itemText(idx) == active_filter.chain:
                        self.interactionChainComboBox.setCurrentIndex(idx)
            else: self.interactionChainComboBox.setCurrentIndex(0)
            self.interactionResTypeComboBox.addItems(str(t) for t in set([x.res_type for x in filtered_data]))
            self.interactionResTypeComboBox.insertItem(0, "Any")
            if self.res_name_filter:
                for idx in range(0, self.interactionResTypeComboBox.count()):
                    if self.interactionResTypeComboBox.itemText(idx) == active_filter.res_type:
                        self.interactionTypeComboBox.setCurrentIndex(idx)
            else: self.interactionResTypeComboBox.setCurrentIndex(0)
            self.interactionResNComboBox.addItems(str(t) for t in set([x.res_number for x in filtered_data]))
            self.interactionResNComboBox.insertItem(0, "Any")
            if self.res_id_filter:
                for idx in range(0, self.interactionResNComboBox.count()):
                    if self.interactionResNComboBox.itemText(idx) == active_filter.res_number:
                        self.interactionResNComboBox.setCurrentIndex(idx)
            else: self.interactionResNComboBox.setCurrentIndex(0)
            self.interactionAtomNameComboBox.addItems(str(t) for t in set([x.atom_name for x in filtered_data]))
            self.interactionAtomNameComboBox.insertItem(0, "Any")
            if self.atom_name_filter:
                for idx in range(0, self.interactionAtomNameComboBox.count()):
                    if self.interactionAtomNameComboBox.itemText(idx) == active_filter.atom_name:
                        self.interactionAtomNameComboBox.setCurrentIndex(idx)
            else: self.interactionAtomNameComboBox.setCurrentIndex(0)
            
    def update_from_interaction_type(self):        
        filtered_items = self.filter_data_from_GUI()
        if not self.chain_filter: 
            self.interactionChainComboBox.clear()
            self.interactionChainComboBox.addItems(str(t) for t in set([x.chain for x in filtered_items]))
            self.interactionChainComboBox.insertItem(0, "Any")
            self.interactionChainComboBox.setCurrentIndex(0)
        if not self.res_name_filter:
            self.interactionResTypeComboBox.clear()
            self.interactionResTypeComboBox.addItems(str(t) for t in set([x.res_type for x in filtered_items]))
            self.interactionResTypeComboBox.insertItem(0, "Any")
            self.interactionResTypeComboBox.setCurrentIndex(0)
        if not self.res_id_filter:
            self.interactionResNComboBox.clear()
            self.interactionResNComboBox.addItems(str(t) for t in set([x.res_number for x in filtered_items]))
            self.interactionResNComboBox.insertItem(0, "Any")
            self.interactionResNComboBox.setCurrentIndex(0)
        if not self.atom_name_filter:
            self.interactionAtomNameComboBox.clear()
            self.interactionAtomNameComboBox.addItems(str(t) for t in set([x.atom_name for x in filtered_items]))
            self.interactionAtomNameComboBox.insertItem(0, "Any")
            self.interactionAtomNameComboBox.setCurrentIndex(0)
        
    def update_from_chain(self):
        filtered_items = self.filter_data_from_GUI()
        if not self.interaction_filter:
            self.interactionTypeComboBox.clear()
            self.interactionTypeComboBox.addItems(str(t) for t in set([x.interaction_type for x in filtered_items]))
            self.interactionTypeComboBox.insertItem(0, "Any")
            self.interactionTypeComboBox.setCurrentIndex(0)
        if not self.res_name_filter:
            self.interactionResTypeComboBox.clear()
            self.interactionResTypeComboBox.addItems(str(t) for t in set([x.res_type for x in filtered_items]))
            self.interactionResTypeComboBox.insertItem(0, "Any")
            self.interactionResTypeComboBox.setCurrentIndex(0)
        if not self.res_id_filter:
            self.interactionResNComboBox.clear()
            self.interactionResNComboBox.addItems(str(t) for t in set([x.res_number for x in filtered_items]))
            self.interactionResNComboBox.insertItem(0, "Any")
            self.interactionResNComboBox.setCurrentIndex(0)
        if not self.atom_name_filter:
            self.interactionAtomNameComboBox.clear()
            self.interactionAtomNameComboBox.addItems(str(t) for t in set([x.atom_name for x in filtered_items]))
            self.interactionAtomNameComboBox.insertItem(0, "Any")
            self.interactionAtomNameComboBox.setCurrentIndex(0)
    
    def update_from_res_type(self):
        filtered_items = self.filter_data_from_GUI()
        if not self.interaction_filter:
            self.interactionTypeComboBox.clear()
            self.interactionTypeComboBox.addItems(str(t) for t in set([x.interaction_type for x in filtered_items]))
            self.interactionTypeComboBox.insertItem(0, "Any")
            self.interactionTypeComboBox.setCurrentIndex(0)
        if not self.chain_filter:
            self.interactionChainComboBox.clear()
            self.interactionChainComboBox.addItems(str(t) for t in set([x.chain for x in filtered_items]))
            self.interactionChainComboBox.insertItem(0, "Any")
            self.interactionChainComboBox.setCurrentIndex(0)
        if not self.res_id_filter:
            self.interactionResNComboBox.clear()
            self.interactionResNComboBox.addItems(str(t) for t in set([x.res_number for x in filtered_items]))
            self.interactionResNComboBox.insertItem(0, "Any")
            self.interactionResNComboBox.setCurrentIndex(0)
        if not self.atom_name_filter:
            self.interactionAtomNameComboBox.clear()
            self.interactionAtomNameComboBox.addItems(str(t) for t in set([x.atom_name for x in filtered_items]))
            self.interactionAtomNameComboBox.insertItem(0, "Any")
            self.interactionAtomNameComboBox.setCurrentIndex(0)
    
    def update_from_res_number(self):
        filtered_items = self.filter_data_from_GUI()
        if not self.interaction_filter:
            self.interactionTypeComboBox.clear()
            self.interactionTypeComboBox.addItems(str(t) for t in set([x.interaction_type for x in filtered_items]))
            self.interactionTypeComboBox.insertItem(0, "Any")
            self.interactionTypeComboBox.setCurrentIndex(0)
        if not self.chain_filter:
            self.interactionChainComboBox.clear()
            self.interactionChainComboBox.addItems(str(t) for t in set([x.chain for x in filtered_items]))
            self.interactionChainComboBox.insertItem(0, "Any")
            self.interactionChainComboBox.setCurrentIndex(0)
        if not self.res_name_filter:
            self.interactionResTypeComboBox.clear()
            self.interactionResTypeComboBox.addItems(str(t) for t in set([x.res_type for x in filtered_items]))
            self.interactionResTypeComboBox.insertItem(0, "Any")
            self.interactionResTypeComboBox.setCurrentIndex(0)
        if not self.atom_name_filter:
            self.interactionAtomNameComboBox.clear()
            self.interactionAtomNameComboBox.addItems(str(t) for t in set([x.atom_name for x in filtered_items]))
            self.interactionAtomNameComboBox.insertItem(0, "Any")
            self.interactionAtomNameComboBox.setCurrentIndex(0)

    def update_from_atom(self):
        filtered_items = self.filter_data_from_GUI()
        if not self.interaction_filter:
            self.interactionTypeComboBox.clear()
            self.interactionTypeComboBox.addItems(str(t) for t in set([x.interaction_type for x in filtered_items]))
            self.interactionTypeComboBox.insertItem(0, "Any")
            self.interactionTypeComboBox.setCurrentIndex(0)
        if not self.chain_filter:
            self.interactionChainComboBox.clear()
            self.interactionChainComboBox.addItems(str(t) for t in set([x.chain for x in filtered_items]))
            self.interactionChainComboBox.insertItem(0, "Any")
            self.interactionChainComboBox.setCurrentIndex(0)
        if not self.res_name_filter:
            self.interactionResTypeComboBox.clear()
            self.interactionResTypeComboBox.addItems(str(t) for t in set([x.res_type for x in filtered_items]))
            self.interactionResTypeComboBox.insertItem(0, "Any")
            self.interactionResTypeComboBox.setCurrentIndex(0)
        if not self.res_id_filter:
            self.interactionResNComboBox.clear()
            self.interactionResNComboBox.addItems(str(t) for t in set([x.res_number for x in filtered_items]))
            self.interactionResNComboBox.insertItem(0, "Any")
            self.interactionResNComboBox.setCurrentIndex(0)
    
    def filter_data_from_obj(self, active_filter):
        filtered_items = None
        if active_filter.interaction_type != None:
            self.interaction_filter = True
            filtered_items = list(filter(lambda x: x.interaction_type == active_filter.interaction_type, self.items))
        else:
            self.interaction_filter = False
        if active_filter.chain != None:
            if filtered_items is None:
                filtered_items = self.items
            self.chain_filter = True
            filtered_items = list(filter(lambda x: x.chain == active_filter.chain, filtered_items))
        else: self.chain_filter = False
        if active_filter.res_type != None:
            if filtered_items is None:
                filtered_items = self.items
            self.res_name_filter = True
            filtered_items = list(filter(lambda x: x.res_type == active_filter.res_type, filtered_items))
        else: self.res_name_filter = False
        if active_filter.res_number != None:
            if filtered_items is None:
                filtered_items = self.items
            self.res_id_filter = True
            filtered_items = list(filter(lambda x: x.res_number == active_filter.res_number, filtered_items))
        else: self.res_id_filter = False
        if active_filter.atom_name != None:
            if filtered_items is None:
                filtered_items = self.items
            self.atom_name_filter = True
            filtered_items = list(filter(lambda x: x.atom_name == active_filter.atom_name, filtered_items))
        else: self.atom_name_filter = False
        if filtered_items is None: return self.items
        return filtered_items
        
    def filter_data_from_GUI(self):
        filtered_items = None
        if self.interactionTypeComboBox.currentText() != 'Any':
            self.interaction_filter = True
            interaction_type = self.interactionTypeComboBox.currentText()
            filtered_items = list(filter(lambda x: x.interaction_type == interaction_type, self.items))
        else:
            self.interaction_filter = False
        if self.interactionChainComboBox.currentText() != 'Any':
            if filtered_items is None:
                filtered_items = self.items
            self.chain_filter = True
            chain = self.interactionChainComboBox.currentText()
            filtered_items = list(filter(lambda x: x.chain == chain, filtered_items))
        else: self.chain_filter = False
        if self.interactionResTypeComboBox.currentText() != 'Any':
            if filtered_items is None:
                filtered_items = self.items
            self.res_name_filter = True
            res_type = self.interactionResTypeComboBox.currentText()
            filtered_items = list(filter(lambda x: x.res_type == res_type, filtered_items))
        else: self.res_name_filter = False
        if self.interactionResNComboBox.currentText() != 'Any':
            if filtered_items is None:
                filtered_items = self.items
            self.res_id_filter = True
            res_n = self.interactionResNComboBox.currentText()
            filtered_items = list(filter(lambda x: x.res_number == res_n, filtered_items))
        else: self.res_id_filter = False
        if self.interactionAtomNameComboBox.currentText() != 'Any':
            if filtered_items is None:
                filtered_items = self.items
            self.atom_name_filter = True
            atom_name = self.interactionAtomNameComboBox.currentText()
            filtered_items = list(filter(lambda x: x.atom_name == atom_name, filtered_items))
        else: self.atom_name_filter = False
        if filtered_items is None: return self.items
        return filtered_items
    
    
    def set_interaction_type(self):
        self.filter.set_interaction_type(self.interactionTypeComboBox.currentText())
        
    def set_filter_wanted(self):
        if self.wantedRadioButton.isChecked():
            self.filter.set_wanted(True)
        else:
            self.filter.set_wanted(False)
    
    def set_filter_unwanted(self):
        if self.unwantedRadioButton.isChecked():
            self.filter.set_wanted(False)
        else:
            self.filter.set_wanted(True)
    
    def get_interaction_obj(self):
        self.filter.set_interaction_type(self.interactionTypeComboBox.currentText())
        self.filter.set_chain(self.interactionChainComboBox.currentText())
        self.filter.set_res_type(self.interactionResTypeComboBox.currentText())
        self.filter.set_res_number(self.interactionResNComboBox.currentText())
        self.filter.set_atom_name(self.interactionAtomNameComboBox.currentText())
        self.accept()
    
    def close_widget(self):
        self.filter = None
        self.accept()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.interactionTypeLabel.setText(_translate("Form", "Select interaction type:"))
        self.wantedRadioButton.setText(_translate("Form", "Wanted"))
        self.unwantedRadioButton.setText(_translate("Form", "Unwanted"))
        self.interactionChainLabel.setText(_translate("Form", "Chain:"))
        self.interactionResTypeLabel.setText(_translate("Form", "Res Type:"))
        self.interactionResNLabel.setText(_translate("Form", "Res #:"))
        self.interactionAtomNameLabel.setText(_translate("Form", "Atom Name:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = Interaction_Dialog(list_example, None)
    MainWindow.show()
    sys.exit(app.exec_())
    # interactions = parse_list_of_items(list_example)
    # print(f"Unique Interactions: {set([x.interaction_type for x in interactions])}")
    # print(f"Unique Chains: {set([x.chain for x in interactions])}")
    # print(f"Unique Res Names: {set([x.res_type for x in interactions])}")
    # print(f"Unique Res IDs: {set([x.res_number for x in interactions])}")
    # print(f"Unique Atom Names: {set([x.atom_name for x in interactions])}")