# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/ligandFilter.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(450, 287)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.ligandNameRadioButton = QtWidgets.QRadioButton(Dialog)
        self.ligandNameRadioButton.setObjectName("ligandNameRadioButton")
        self.gridLayout.addWidget(self.ligandNameRadioButton, 0, 0, 1, 3)
        self.ligandSubstructureRadioButton = QtWidgets.QRadioButton(Dialog)
        self.ligandSubstructureRadioButton.setObjectName("ligandSubstructureRadioButton")
        self.gridLayout.addWidget(self.ligandSubstructureRadioButton, 0, 5, 1, 2)
        self.ligandNameLabel = QtWidgets.QLabel(Dialog)
        self.ligandNameLabel.setObjectName("ligandNameLabel")
        self.gridLayout.addWidget(self.ligandNameLabel, 1, 0, 1, 1)
        self.ligandNameLineEdit = QtWidgets.QLineEdit(Dialog)
        self.ligandNameLineEdit.setObjectName("ligandNameLineEdit")
        self.gridLayout.addWidget(self.ligandNameLineEdit, 1, 1, 1, 5)
        self.substructureLabel = QtWidgets.QLabel(Dialog)
        self.substructureLabel.setObjectName("substructureLabel")
        self.gridLayout.addWidget(self.substructureLabel, 2, 0, 1, 2)
        self.substructureLineEdit = QtWidgets.QLineEdit(Dialog)
        self.substructureLineEdit.setObjectName("substructureLineEdit")
        self.gridLayout.addWidget(self.substructureLineEdit, 2, 3, 1, 3)
        self.coordinatesCheckBox = QtWidgets.QCheckBox(Dialog)
        self.coordinatesCheckBox.setObjectName("coordinatesCheckBox")
        self.gridLayout.addWidget(self.coordinatesCheckBox, 3, 0, 1, 4)
        self.coordinatesLabel = QtWidgets.QLabel(Dialog)
        self.coordinatesLabel.setObjectName("coordinatesLabel")
        self.gridLayout.addWidget(self.coordinatesLabel, 4, 0, 1, 3)
        self.cutoffLabel = QtWidgets.QLabel(Dialog)
        self.cutoffLabel.setObjectName("cutoffLabel")
        self.gridLayout.addWidget(self.cutoffLabel, 4, 5, 1, 1)
        self.indexLabel = QtWidgets.QLabel(Dialog)
        self.indexLabel.setObjectName("indexLabel")
        self.gridLayout.addWidget(self.indexLabel, 4, 6, 1, 1)
        self.xDoubleSpinBox = QtWidgets.QDoubleSpinBox(Dialog)
        self.xDoubleSpinBox.setObjectName("xDoubleSpinBox")
        self.gridLayout.addWidget(self.xDoubleSpinBox, 5, 0, 1, 2)
        self.yDoubleSpinBox = QtWidgets.QDoubleSpinBox(Dialog)
        self.yDoubleSpinBox.setObjectName("yDoubleSpinBox")
        self.gridLayout.addWidget(self.yDoubleSpinBox, 5, 2, 1, 2)
        self.zDoubleSpinBox = QtWidgets.QDoubleSpinBox(Dialog)
        self.zDoubleSpinBox.setObjectName("zDoubleSpinBox")
        self.gridLayout.addWidget(self.zDoubleSpinBox, 5, 4, 1, 1)
        self.cutoffDoubleSpinBox = QtWidgets.QDoubleSpinBox(Dialog)
        self.cutoffDoubleSpinBox.setObjectName("cutoffDoubleSpinBox")
        self.gridLayout.addWidget(self.cutoffDoubleSpinBox, 5, 5, 1, 1)
        self.indexSpinBox = QtWidgets.QSpinBox(Dialog)
        self.indexSpinBox.setObjectName("indexSpinBox")
        self.gridLayout.addWidget(self.indexSpinBox, 5, 6, 1, 1)
        self.okCancelButtonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.okCancelButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.okCancelButtonBox.setObjectName("okCancelButtonBox")
        self.gridLayout.addWidget(self.okCancelButtonBox, 6, 5, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.ligandNameRadioButton.setText(_translate("Dialog", "Ligand Name"))
        self.ligandSubstructureRadioButton.setText(_translate("Dialog", "Substructure Match"))
        self.ligandNameLabel.setText(_translate("Dialog", "Name:"))
        self.substructureLabel.setText(_translate("Dialog", "Substructure:"))
        self.coordinatesCheckBox.setText(_translate("Dialog", "Include coordinates"))
        self.coordinatesLabel.setText(_translate("Dialog", "Coordinates (x, y, z):"))
        self.cutoffLabel.setText(_translate("Dialog", "Cutoff:"))
        self.indexLabel.setText(_translate("Dialog", "Index:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
