# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/selectReceptor.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_selectReceptorForm(QtWidgets.QDialog, object):
    def __init__(self, parent=None):
        QtWidgets.QDialog.__init__(self, parent)
        self.setupUi(self)
        
    def setupUi(self, selectReceptorForm):
        selectReceptorForm.setObjectName("selectReceptorForm")
        selectReceptorForm.resize(496, 218)
        self.selectDirectoryLabel = QtWidgets.QLabel(selectReceptorForm)
        self.selectDirectoryLabel.setGeometry(QtCore.QRect(20, 20, 121, 17))
        self.selectDirectoryLabel.setObjectName("selectDirectoryLabel")
        self.browseDirectorylineEdit = QtWidgets.QLineEdit(selectReceptorForm)
        self.browseDirectorylineEdit.setGeometry(QtCore.QRect(160, 20, 201, 25))
        self.browseDirectorylineEdit.setObjectName("browseDirectorylineEdit")
        self.browseDirectoryPushButton = QtWidgets.QPushButton(selectReceptorForm)
        self.browseDirectoryPushButton.setGeometry(QtCore.QRect(380, 20, 89, 25))
        self.browseDirectoryPushButton.setObjectName("browseDirectoryPushButton")
        self.selectFileListLabel = QtWidgets.QLabel(selectReceptorForm)
        self.selectFileListLabel.setGeometry(QtCore.QRect(20, 70, 101, 17))
        self.selectFileListLabel.setObjectName("selectFileListLabel")
        self.selectListFileLineEdit = QtWidgets.QLineEdit(selectReceptorForm)
        self.selectListFileLineEdit.setGeometry(QtCore.QRect(160, 70, 201, 25))
        self.selectListFileLineEdit.setObjectName("selectListFileLineEdit")
        self.browseFileListPushButton = QtWidgets.QPushButton(selectReceptorForm)
        self.browseFileListPushButton.setGeometry(QtCore.QRect(380, 70, 89, 25))
        self.browseFileListPushButton.setObjectName("browseFileListPushButton")
        self.listFileScrollArea = QtWidgets.QScrollArea(selectReceptorForm)
        self.listFileScrollArea.setGeometry(QtCore.QRect(20, 120, 451, 91))
        self.listFileScrollArea.setWidgetResizable(True)
        self.listFileScrollArea.setObjectName("listFileScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 449, 89))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.listFileListWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.listFileListWidget.setGeometry(QtCore.QRect(-5, 0, 461, 192))
        self.listFileListWidget.setObjectName("listFileListWidget")
        self.listFileScrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(selectReceptorForm)
        QtCore.QMetaObject.connectSlotsByName(selectReceptorForm)

    def retranslateUi(self, selectReceptorForm):
        _translate = QtCore.QCoreApplication.translate
        selectReceptorForm.setWindowTitle(_translate("selectReceptorForm", "Select receptor(s)"))
        self.selectDirectoryLabel.setText(_translate("selectReceptorForm", "Select directory:"))
        self.browseDirectoryPushButton.setText(_translate("selectReceptorForm", "Browse"))
        self.selectFileListLabel.setText(_translate("selectReceptorForm", "Select list file:"))
        self.browseFileListPushButton.setText(_translate("selectReceptorForm", "Browse"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    selectReceptorForm = QtWidgets.QWidget()
    ui = Ui_selectReceptorForm()
    ui.setupUi(selectReceptorForm)
    selectReceptorForm.show()
    sys.exit(app.exec_())
